def on_up_pressed():
    global facingdirection
    facingdirection = 3
    animation.run_image_animation(mySprite,
        [img("""
            . . . . . . f f f f . . . . . .
            . . . . f f e e e e f f . . . .
            . . . f e e e f f e e e f . . .
            . . f f f f f 2 2 f f f f f . .
            . . f f e 2 e 2 2 e 2 e f f . .
            . . f e 2 f 2 f f 2 f 2 e f . .
            . . f f f 2 2 e e 2 2 f f f . .
            . f f e f 2 f e e f 2 f e f f .
            . f e e f f e e e e f e e e f .
            . . f e e e e e e e e e e f . .
            . . . f e e e e e e e e f . . .
            . . e 4 f f f f f f f f 4 e . .
            . . 4 d f 2 2 2 2 2 2 f d 4 . .
            . . 4 4 f 4 4 4 4 4 4 f 4 4 . .
            . . . . . f f f f f f . . . . .
            . . . . . f f . . f f . . . . .
        """),
            img("""
                . . . . . . . . . . . . . . . . 
                        . . . . . . f f f f . . . . . . 
                        . . . . f f e e e e f f . . . . 
                        . . . f e e e f f e e e f . . . 
                        . . . f f f f 2 2 f f f f . . . 
                        . . f f e 2 e 2 2 e 2 e f f . . 
                        . . f e 2 f 2 f f f 2 f e f . . 
                        . . f f f 2 f e e 2 2 f f f . . 
                        . . f e 2 f f e e 2 f e e f . . 
                        . f f e f f e e e f e e e f f . 
                        . f f e e e e e e e e e e f f . 
                        . . . f e e e e e e e e f . . . 
                        . . . e f f f f f f f f 4 e . . 
                        . . . 4 f 2 2 2 2 2 e d d 4 . . 
                        . . . e f f f f f f e e 4 . . . 
                        . . . . f f f . . . . . . . . .
            """),
            img("""
                . . . . . . f f f f . . . . . . 
                        . . . . f f e e e e f f . . . . 
                        . . . f e e e f f e e e f . . . 
                        . . f f f f f 2 2 f f f f f . . 
                        . . f f e 2 e 2 2 e 2 e f f . . 
                        . . f e 2 f 2 f f 2 f 2 e f . . 
                        . . f f f 2 2 e e 2 2 f f f . . 
                        . f f e f 2 f e e f 2 f e f f . 
                        . f e e f f e e e e f e e e f . 
                        . . f e e e e e e e e e e f . . 
                        . . . f e e e e e e e e f . . . 
                        . . e 4 f f f f f f f f 4 e . . 
                        . . 4 d f 2 2 2 2 2 2 f d 4 . . 
                        . . 4 4 f 4 4 4 4 4 4 f 4 4 . . 
                        . . . . . f f f f f f . . . . . 
                        . . . . . f f . . f f . . . . .
            """),
            img("""
                . . . . . . . . . . . . . . . . 
                        . . . . . . f f f f . . . . . . 
                        . . . . f f e e e e f f . . . . 
                        . . . f e e e f f e e e f . . . 
                        . . . f f f f 2 2 f f f f . . . 
                        . . f f e 2 e 2 2 e 2 e f f . . 
                        . . f e f 2 f f f 2 f 2 e f . . 
                        . . f f f 2 2 e e f 2 f f f . . 
                        . . f e e f 2 e e f f 2 e f . . 
                        . f f e e e f e e e f f e f f . 
                        . f f e e e e e e e e e e f f . 
                        . . . f e e e e e e e e f . . . 
                        . . e 4 f f f f f f f f e . . . 
                        . . 4 d d e 2 2 2 2 2 f 4 . . . 
                        . . . 4 e e f f f f f f e . . . 
                        . . . . . . . . . f f f . . . .
            """)],
        100,
        False)
controller.up.on_event(ControllerButtonEvent.PRESSED, on_up_pressed)

def on_a_pressed():
    global projectile, EnemyHitBoolean
    if facingdirection == 1:
        projectile = sprites.create_projectile_from_sprite(img("""
                . . . . . . . . . . . . . . . . 
                            . . . . . . . . . . . . . . . . 
                            . . . . . . . . . . . . . . . . 
                            . . . . . . . . . . . . . . . . 
                            . . . . . . . . . . . . . . . . 
                            . . . . . . . . . . . . . . . . 
                            . . . . . . . . . . . . . . . . 
                            . . . . . . . . . . . . . . . . 
                            . . . . . . . . . . . . . . . . 
                            . . . . . . . . . . . . . . . . 
                            . . . . . . . . . . . . . . . . 
                            . . . . . . . . . . . . . . . . 
                            . . . . . . . . . . . . . . . . 
                            . . . . . . . . . . . . . . . . 
                            . . . . . . . . . . . . . . . . 
                            . . . . . . . . . . . . . . . .
            """),
            mySprite,
            50,
            50)
        animation.run_image_animation(mySprite,
            [img("""
                    ........................
                                ....ffffff..............
                                ..ffeeeef2f.............
                                .ffeeeef222f............
                                .feeeffeeeef...cc.......
                                .ffffee2222ef.cdc.......
                                .fe222ffffe2fcddc.......
                                fffffffeeeffcddc........
                                ffe44ebf44ecddc.........
                                fee4d41fddecdc..........
                                .feee4d3dedccc..........
                                ..ffee44e4dde...........
                                ...f222244ee............
                                ...f2222e2f.............
                                ...f444455f.............
                                ....ffffff..............
                                .....fff................
                                ........................
                                ........................
                                ........................
                                ........................
                                ........................
                                ........................
                                ........................
                """),
                img("""
                    ........................
                                .......fff..............
                                ....fffff2f.............
                                ..ffeeeee22ff...........
                                .ffeeeeee222ff..........
                                .feeeefffeeeef..........
                                .fffffeee2222ef.........
                                fffe222fffffe2f.........
                                fffffffffeeefff.....cc..
                                fefe44ebbf44eef...ccdc..
                                .fee4d4bbfddef..ccddcc..
                                ..feee4dd3ddfeecdddc....
                                ...f2222222eeddcdcc.....
                                ...f444445e44ddccc......
                                ...ffffffffeeee.........
                                ...fff...ff.............
                                ........................
                                ........................
                                ........................
                                ........................
                                ........................
                                ........................
                                ........................
                                ........................
                """),
                img("""
                    .......ff...............
                                ....ffff2ff.............
                                ..ffeeeef2ff............
                                .ffeeeeef22ff...........
                                .feeeeffeeeef...........
                                .fffffee2222ef..........
                                fffe222ffffe2f..........
                                ffffffffeeefff..........
                                fefe44ebf44eef..........
                                .fee4d4bfddef...........
                                ..feee4d3dee.c..........
                                ...f2222eeddeccccccc....
                                ...f444e44ddecddddd.....
                                ...fffffeeee.ccccc......
                                ..ffffffff...c..........
                                ..fff..ff...............
                                ........................
                                ........................
                                ........................
                                ........................
                                ........................
                                ........................
                                ........................
                                ........................
                """),
                img("""
                    ....ffffff..............
                                ..ffeeeef2f.............
                                .ffeeeef222f............
                                .feeeffeeeef............
                                .ffffee2222ef...........
                                .fe222ffffe2f...........
                                fffffffeeefff...........
                                ffe44ebf44eef...........
                                fee4d41fddef............
                                .feee4d3ddf.............
                                ..fdde444ef.............
                                ..fdde22ccc.............
                                ...eef22cdc.............
                                ...f4444cddc............
                                ....fffffcddc...........
                                .....fff..cddc..........
                                ...........cdc..........
                                ............cc..........
                                ........................
                                ........................
                                ........................
                                ........................
                                ........................
                                ........................
                """)],
            100,
            False)
        if mySprite.overlaps_with(myEnemy):
            EnemyHitBoolean = 1
        else:
            EnemyHitBoolean = 0
    if facingdirection == 2:
        projectile = sprites.create_projectile_from_sprite(img("""
                . . . . . . . . . . . . . . . . 
                            . . . . . . . . . . . . . . . . 
                            . . . . . . . . . . . . . . . . 
                            . . . . . . . . . . . . . . . . 
                            . . . . . . . . . . . . . . . . 
                            . . . . . . . . . . . . . . . . 
                            . . . . . . . . . . . . . . . . 
                            . . . . . . . . . . . . . . . . 
                            . . . . . . . . . . . . . . . . 
                            . . . . . . . . . . . . . . . . 
                            . . . . . . . . . . . . . . . . 
                            . . . . . . . . . . . . . . . . 
                            . . . . . . . . . . . . . . . . 
                            . . . . . . . . . . . . . . . . 
                            . . . . . . . . . . . . . . . . 
                            . . . . . . . . . . . . . . . .
            """),
            mySprite,
            50,
            50)
        animation.run_image_animation(mySprite,
            [img("""
                    ..............ffffff....
                                .............f2feeeeff..
                                ............f222feeeeff.
                                .......cc...feeeeffeeef.
                                .......cdc.fe2222eeffff.
                                .......cddcf2effff222ef.
                                ........cddcffeeefffffff
                                .........cddce44fbe44eff
                                ..........cdceddf14d4eef
                                ..........cccded3d4eeef.
                                ...........edd4e44eeff..
                                ............ee442222f...
                                .............f2e2222f...
                                .............f554444f...
                                ..............ffffff....
                                ................fff.....
                                ........................
                                ........................
                                ........................
                                ........................
                                ........................
                                ........................
                                ........................
                                ........................
                """),
                img("""
                    ........................
                                ..............fff.......
                                .............f2fffff....
                                ...........ff22eeeeeff..
                                ..........ff222eeeeeeff.
                                ..........feeeefffeeeef.
                                .........fe2222eeefffff.
                                .........f2efffff222efff
                                ..cc.....fffeeefffffffff
                                ..cdcc...fee44fbbe44efef
                                ..ccddcc..feddfbb4d4eef.
                                ....cdddceefdd3dd4eeef..
                                .....ccdcddee2222222f...
                                ......cccdd44e544444f...
                                .........eeeeffffffff...
                                .............ff...fff...
                                ........................
                                ........................
                                ........................
                                ........................
                                ........................
                                ........................
                                ........................
                                ........................
                """),
                img("""
                    ...............ff.......
                                .............ff2ffff....
                                ............ff2feeeeff..
                                ...........ff22feeeeeff.
                                ...........feeeeffeeeef.
                                ..........fe2222eefffff.
                                ..........f2effff222efff
                                ..........fffeeeffffffff
                                ..........fee44fbe44efef
                                ...........feddfb4d4eef.
                                ..........c.eed3d4eeef..
                                ....ccccccceddee2222f...
                                .....dddddcedd44e444f...
                                ......ccccc.eeeefffff...
                                ..........c...ffffffff..
                                ...............ff..fff..
                                ........................
                                ........................
                                ........................
                                ........................
                                ........................
                                ........................
                                ........................
                                ........................
                """),
                img("""
                    ..............ffffff....
                                .............f2feeeeff..
                                ............f222feeeeff.
                                ............feeeeffeeef.
                                ...........fe2222eeffff.
                                ...........f2effff222ef.
                                ...........fffeeefffffff
                                ...........fee44fbe44eff
                                ............feddf14d4eef
                                .............fdd3d4eeef.
                                .............fe444eddf..
                                .............ccc22eddf..
                                .............cdc22fee...
                                ............cddc4444f...
                                ...........cddcfffff....
                                ..........cddc..fff.....
                                ..........cdc...........
                                ..........cc............
                                ........................
                                ........................
                                ........................
                                ........................
                                ........................
                                ........................
                """)],
            100,
            False)
        if mySprite.overlaps_with(myEnemy):
            EnemyHitBoolean = 1
        else:
            EnemyHitBoolean = 0
    if facingdirection == 3:
        projectile = sprites.create_projectile_from_sprite(img("""
                . . . . . . . . . . . . . . . . 
                            . . . . . . . . . . . . . . . . 
                            . . . . . . . . . . . . . . . . 
                            . . . . . . . . . . . . . . . . 
                            . . . . . . . . . . . . . . . . 
                            . . . . . . . . . . . . . . . . 
                            . . . . . . . . . . . . . . . . 
                            . . . . . . . . . . . . . . . . 
                            . . . . . . . . . . . . . . . . 
                            . . . . . . . . . . . . . . . . 
                            . . . . . . . . . . . . . . . . 
                            . . . . . . . . . . . . . . . . 
                            . . . . . . . . . . . . . . . . 
                            . . . . . . . . . . . . . . . . 
                            . . . . . . . . . . . . . . . . 
                            . . . . . . . . . . . . . . . .
            """),
            mySprite,
            50,
            50)
        animation.run_image_animation(mySprite,
            [img("""
                    ........................
                                .....ffff...............
                                ...fff22fff.............
                                ..fff2222fff............
                                .fffeeeeeefff...........
                                .ffe222222eef...........
                                .fe2ffffff2ef...........
                                .ffffeeeeffff...........
                                ffefbf44fbfeff..........
                                fee41fddf14eef..........
                                .ffffdddd3eef...........
                                fddddf444eef............
                                fbbbbf2222f4e...........
                                fbbbbf2222fd4...........
                                .fccf45544f44...........
                                ..ffffffff..............
                                ....ff..ff..............
                                ........................
                                ........................
                                ........................
                                ........................
                                ........................
                                ........................
                                ........................
                """),
                img("""
                    ........................
                                ......ffff..............
                                ....fff22fff............
                                ...fff2222fff...........
                                ..fffeeeeeefff..........
                                ..ffe222222eef..........
                                ..fe2ffffff2ef..........
                                ..ffffeeeeffff..........
                                .ffefbf44fbfeff.........
                                .fee41fddf14eef.........
                                fdfee3dddd4eff..........
                                fbffee444edd4e..........
                                fbf4f2222edde...........
                                fcf.f22cccee............
                                .ff.f44cdc4f............
                                ....fffddcff............
                                .....fddcff.............
                                ....cddc................
                                ....cdc.................
                                ....cc..................
                                ........................
                                ........................
                                ........................
                                ........................
                """),
                img("""
                    ........................
                                ........................
                                .......ff...............
                                .....ff22ff.............
                                ...fff2222fff...........
                                ..fff222222fff..........
                                ..fff222222fff..........
                                ..feeeeeeeeeeff.........
                                .ffe22222222eff.........
                                .fffffeeeefffff.........
                                fdfefbf44fbfeff.........
                                fbfe41fddf14ef..........
                                fbffe4dddd4efe..........
                                fcfef22222f4e...........
                                .ff4f44554f4e...........
                                ....ffffffdde...........
                                .....ffffedde...........
                                ..........ee............
                                .........ccc............
                                ........cc1cc...........
                                .........c1c............
                                .........c1c............
                                .........c1c............
                                .........c1c............
                """),
                img("""
                    ......ffff..............
                                ....fff22fff............
                                ...fff2222fff...........
                                ..fffeeeeeefff..........
                                ..ffe222222eef..........
                                ..fe2ffffff2ef..........
                                ..ffffeeeeffff......ccc.
                                .ffefbf44fbfeff....cddc.
                                .ffefbf44fbfeff...cddc..
                                .fee43dddd34eef.ccddc...
                                fdfeeddddd4eeffecddc....
                                fbffee4444ee4fddccc.....
                                fbf4f222222f1edde.......
                                fcf.f222222f44ee........
                                .ff.f445544f............
                                ....ffffffff............
                                .....ff..ff.............
                                ........................
                                ........................
                                ........................
                                ........................
                                ........................
                                ........................
                                ........................
                """)],
            100,
            False)
        if mySprite.overlaps_with(myEnemy):
            EnemyHitBoolean = 1
        else:
            EnemyHitBoolean = 0
    if facingdirection == 4:
        projectile = sprites.create_projectile_from_sprite(img("""
                . . . . . . . . . . . . . . . . 
                            . . . . . . . . . . . . . . . . 
                            . . . . . . . . . . . . . . . . 
                            . . . . . . . . . . . . . . . . 
                            . . . . . . . . . . . . . . . . 
                            . . . . . . . . . . . . . . . . 
                            . . . . . . . . . . . . . . . . 
                            . . . . . . . . . . . . . . . . 
                            . . . . . . . . . . . . . . . . 
                            . . . . . . . . . . . . . . . . 
                            . . . . . . . . . . . . . . . . 
                            . . . . . . . . . . . . . . . . 
                            . . . . . . . . . . . . . . . . 
                            . . . . . . . . . . . . . . . . 
                            . . . . . . . . . . . . . . . . 
                            . . . . . . . . . . . . . . . .
            """),
            mySprite,
            50,
            50)
        animation.run_image_animation(mySprite,
            [img("""
                    ........................
                                .....ffff...............
                                ...fff22fff.............
                                ..fff2222fff............
                                .fffeeeeeefff...........
                                .ffe222222eef...........
                                .fe2ffffff2ef...........
                                .ffffeeeeffff...........
                                ffefbf44fbfeff..........
                                fee41fddf14eef..........
                                .ffffdddd3eef...........
                                fddddf444eef............
                                fbbbbf2222f4e...........
                                fbbbbf2222fd4...........
                                .fccf45544f44...........
                                ..ffffffff..............
                                ....ff..ff..............
                                ........................
                                ........................
                                ........................
                                ........................
                                ........................
                                ........................
                                ........................
                """),
                img("""
                    ........................
                                ......ffff..............
                                ....fff22fff............
                                ...fff2222fff...........
                                ..fffeeeeeefff..........
                                ..ffe222222eef..........
                                ..fe2ffffff2ef..........
                                ..ffffeeeeffff..........
                                .ffefbf44fbfeff.........
                                .fee41fddf14eef.........
                                fdfee3dddd4eff..........
                                fbffee444edd4e..........
                                fbf4f2222edde...........
                                fcf.f22cccee............
                                .ff.f44cdc4f............
                                ....fffddcff............
                                .....fddcff.............
                                ....cddc................
                                ....cdc.................
                                ....cc..................
                                ........................
                                ........................
                                ........................
                                ........................
                """),
                img("""
                    ........................
                                ........................
                                .......ff...............
                                .....ff22ff.............
                                ...fff2222fff...........
                                ..fff222222fff..........
                                ..fff222222fff..........
                                ..feeeeeeeeeeff.........
                                .ffe22222222eff.........
                                .fffffeeeefffff.........
                                fdfefbf44fbfeff.........
                                fbfe41fddf14ef..........
                                fbffe4dddd4efe..........
                                fcfef22222f4e...........
                                .ff4f44554f4e...........
                                ....ffffffdde...........
                                .....ffffedde...........
                                ..........ee............
                                .........ccc............
                                ........cc1cc...........
                                .........c1c............
                                .........c1c............
                                .........c1c............
                                .........c1c............
                """),
                img("""
                    ......ffff..............
                                ....fff22fff............
                                ...fff2222fff...........
                                ..fffeeeeeefff..........
                                ..ffe222222eef..........
                                ..fe2ffffff2ef..........
                                ..ffffeeeeffff......ccc.
                                .ffefbf44fbfeff....cddc.
                                .ffefbf44fbfeff...cddc..
                                .fee43dddd34eef.ccddc...
                                fdfeeddddd4eeffecddc....
                                fbffee4444ee4fddccc.....
                                fbf4f222222f1edde.......
                                fcf.f222222f44ee........
                                .ff.f445544f............
                                ....ffffffff............
                                .....ff..ff.............
                                ........................
                                ........................
                                ........................
                                ........................
                                ........................
                                ........................
                                ........................
                """)],
            100,
            False)
        if mySprite.overlaps_with(myEnemy):
            EnemyHitBoolean = 1
        else:
            EnemyHitBoolean = 0
    if EnemyHitBoolean == 1:
        statusbar.value += SwordStrength
    if statusbar.value == 0:
        sprites.destroy(myEnemy)
controller.A.on_event(ControllerButtonEvent.PRESSED, on_a_pressed)

def on_left_pressed():
    global facingdirection
    facingdirection = 2
    animation.run_image_animation(mySprite,
        [img("""
                . . . . f f f f f f . . . . . . 
                        . . . f 2 f e e e e f f . . . . 
                        . . f 2 2 2 f e e e e f f . . . 
                        . . f e e e e f f e e e f . . . 
                        . f e 2 2 2 2 e e f f f f . . . 
                        . f 2 e f f f f 2 2 2 e f . . . 
                        . f f f e e e f f f f f f f . . 
                        . f e e 4 4 f b e 4 4 e f f . . 
                        . . f e d d f 1 4 d 4 e e f . . 
                        . . . f 3 d d d 4 e e e f . . . 
                        . . . f e 4 4 4 e e f f . . . . 
                        . . . f 2 2 2 e d d 4 . . . . . 
                        . . . f 2 2 2 e d d e . . . . . 
                        . . . f 5 5 4 f e e f . . . . . 
                        . . . . f f f f f f . . . . . . 
                        . . . . . . f f f . . . . . . .
            """),
            img("""
                . . . . . . . . . . . . . . . . 
                        . . . . f f f f f f . . . . . . 
                        . . . f 2 f e e e e f f . . . . 
                        . . f 2 2 2 f e e e e f f . . . 
                        . . f e e e e f f e e e f . . . 
                        . f e 2 2 2 2 e e f f f f . . . 
                        . f 2 e f f f f 2 2 2 e f . . . 
                        . f f f e e e f f f f f f f . . 
                        . f e e 4 4 f b e 4 4 e f f . . 
                        . . f e d d f 1 4 d 4 e e f . . 
                        . . . f 3 d d e e e e e f . . . 
                        . . . f e 4 e d d 4 f . . . . . 
                        . . . f 2 2 e d d e f . . . . . 
                        . . f f 5 5 f e e f f f . . . . 
                        . . f f f f f f f f f f . . . . 
                        . . . f f f . . . f f . . . . .
            """),
            img("""
                . . . . f f f f f f . . . . . . 
                        . . . f 2 f e e e e f f . . . . 
                        . . f 2 2 2 f e e e e f f . . . 
                        . . f e e e e f f e e e f . . . 
                        . f e 2 2 2 2 e e f f f f . . . 
                        . f 2 e f f f f 2 2 2 e f . . . 
                        . f f f e e e f f f f f f f . . 
                        . f e e 4 4 f b e 4 4 e f f . . 
                        . . f e d d f 1 4 d 4 e e f . . 
                        . . . f 3 d d d 4 e e e f . . . 
                        . . . f e 4 4 4 e e f f . . . . 
                        . . . f 2 2 2 e d d 4 . . . . . 
                        . . . f 2 2 2 e d d e . . . . . 
                        . . . f 5 5 4 f e e f . . . . . 
                        . . . . f f f f f f . . . . . . 
                        . . . . . . f f f . . . . . . .
            """),
            img("""
                . . . . . . . . . . . . . . . . 
                        . . . . f f f f f f . . . . . . 
                        . . . f 2 f e e e e f f . . . . 
                        . . f 2 2 2 f e e e e f f . . . 
                        . . f e e e e f f e e e f . . . 
                        . f e 2 2 2 2 e e f f f f . . . 
                        . f 2 e f f f f 2 2 2 e f . . . 
                        . f f f e e e f f f f f f f . . 
                        . f e e 4 4 f b e 4 4 e f f . . 
                        . . f e d d f 1 4 d 4 e e f . . 
                        . . . f 3 d d d 4 e e e f . . . 
                        . . . f e 4 4 4 e d d 4 . . . . 
                        . . . f 2 2 2 2 e d d e . . . . 
                        . . f f 5 5 4 4 f e e f . . . . 
                        . . f f f f f f f f f f . . . . 
                        . . . f f f . . . f f . . . . .
            """)],
        100,
        False)
controller.left.on_event(ControllerButtonEvent.PRESSED, on_left_pressed)

def on_right_pressed():
    global facingdirection
    facingdirection = 1
    animation.run_image_animation(mySprite,
        [img("""
                . . . . . . f f f f f f . . . . 
                        . . . . f f e e e e f 2 f . . . 
                        . . . f f e e e e f 2 2 2 f . . 
                        . . . f e e e f f e e e e f . . 
                        . . . f f f f e e 2 2 2 2 e f . 
                        . . . f e 2 2 2 f f f f e 2 f . 
                        . . f f f f f f f e e e f f f . 
                        . . f f e 4 4 e b f 4 4 e e f . 
                        . . f e e 4 d 4 1 f d d e f . . 
                        . . . f e e e 4 d d d 3 f . . . 
                        . . . . f f e e 4 4 4 e f . . . 
                        . . . . . 4 d d e 2 2 2 f . . . 
                        . . . . . e d d e 2 2 2 f . . . 
                        . . . . . f e e f 4 5 5 f . . . 
                        . . . . . . f f f f f f . . . . 
                        . . . . . . . f f f . . . . . .
            """),
            img("""
                . . . . . . . . . . . . . . . . 
                        . . . . . . f f f f f f . . . . 
                        . . . . f f e e e e f 2 f . . . 
                        . . . f f e e e e f 2 2 2 f . . 
                        . . . f e e e f f e e e e f . . 
                        . . . f f f f e e 2 2 2 2 e f . 
                        . . . f e 2 2 2 f f f f e 2 f . 
                        . . f f f f f f f e e e f f f . 
                        . . f f e 4 4 e b f 4 4 e e f . 
                        . . f e e 4 d 4 1 f d d e f . . 
                        . . . f e e e e e d d 3 f . . . 
                        . . . . . f 4 d d e 4 e f . . . 
                        . . . . . f e d d e 2 2 f . . . 
                        . . . . f f f e e f 5 5 f f . . 
                        . . . . f f f f f f f f f f . . 
                        . . . . . f f . . . f f f . . .
            """),
            img("""
                . . . . . . f f f f f f . . . . 
                        . . . . f f e e e e f 2 f . . . 
                        . . . f f e e e e f 2 2 2 f . . 
                        . . . f e e e f f e e e e f . . 
                        . . . f f f f e e 2 2 2 2 e f . 
                        . . . f e 2 2 2 f f f f e 2 f . 
                        . . f f f f f f f e e e f f f . 
                        . . f f e 4 4 e b f 4 4 e e f . 
                        . . f e e 4 d 4 1 f d d e f . . 
                        . . . f e e e 4 d d d 3 f . . . 
                        . . . . f f e e 4 4 4 e f . . . 
                        . . . . . 4 d d e 2 2 2 f . . . 
                        . . . . . e d d e 2 2 2 f . . . 
                        . . . . . f e e f 4 5 5 f . . . 
                        . . . . . . f f f f f f . . . . 
                        . . . . . . . f f f . . . . . .
            """),
            img("""
                . . . . . . . . . . . . . . . . 
                        . . . . . . f f f f f f . . . . 
                        . . . . f f e e e e f 2 f . . . 
                        . . . f f e e e e f 2 2 2 f . . 
                        . . . f e e e f f e e e e f . . 
                        . . . f f f f e e 2 2 2 2 e f . 
                        . . . f e 2 2 2 f f f f e 2 f . 
                        . . f f f f f f f e e e f f f . 
                        . . f f e 4 4 e b f 4 4 e e f . 
                        . . f e e 4 d 4 1 f d d e f . . 
                        . . . f e e e 4 d d d 3 f . . . 
                        . . . . 4 d d e 4 4 4 e f . . . 
                        . . . . e d d e 2 2 2 2 f . . . 
                        . . . . f e e f 4 4 5 5 f f . . 
                        . . . . f f f f f f f f f f . . 
                        . . . . . f f . . . f f f . . .
            """)],
        100,
        False)
controller.right.on_event(ControllerButtonEvent.PRESSED, on_right_pressed)

def on_down_pressed():
    global facingdirection
    facingdirection = 4
    animation.run_image_animation(mySprite,
        [img("""
                . . . . . . f f f f . . . . . . 
                        . . . . f f f 2 2 f f f . . . . 
                        . . . f f f 2 2 2 2 f f f . . . 
                        . . f f f e e e e e e f f f . . 
                        . . f f e 2 2 2 2 2 2 e e f . . 
                        . . f e 2 f f f f f f 2 e f . . 
                        . . f f f f e e e e f f f f . . 
                        . f f e f b f 4 4 f b f e f f . 
                        . f e e 4 1 f d d f 1 4 e e f . 
                        . . f e e 3 d d d d 3 e e f . . 
                        . . . f e e 4 4 4 4 e e f . . . 
                        . . e 4 f 2 2 2 2 2 2 f 4 e . . 
                        . . 4 d f 2 2 2 2 2 2 f d 4 . . 
                        . . 4 4 f 4 4 5 5 4 4 f 4 4 . . 
                        . . . . . f f f f f f . . . . . 
                        . . . . . f f . . f f . . . . .
            """),
            img("""
                . . . . . . . . . . . . . . . . 
                        . . . . . . f f f f . . . . . . 
                        . . . . f f f 2 2 f f f . . . . 
                        . . . f f f 2 2 2 2 f f f . . . 
                        . . f f f e e e e e e f f f . . 
                        . . f f e 2 2 2 2 2 2 e e f . . 
                        . f f e 2 f f f f f f 2 e f f . 
                        . f f f f f e e e e f f f f f . 
                        . . f e f b f 4 4 f b f e f . . 
                        . . f e 4 1 f d d f 1 4 e f . . 
                        . . . f e 4 d d d d 4 e f e . . 
                        . . f e f 2 2 2 2 e d d 4 e . . 
                        . . e 4 f 2 2 2 2 e d d e . . . 
                        . . . . f 4 4 5 5 f e e . . . . 
                        . . . . f f f f f f f . . . . . 
                        . . . . f f f . . . . . . . . .
            """),
            img("""
                . . . . . . f f f f . . . . . . 
                        . . . . f f f 2 2 f f f . . . . 
                        . . . f f f 2 2 2 2 f f f . . . 
                        . . f f f e e e e e e f f f . . 
                        . . f f e 2 2 2 2 2 2 e e f . . 
                        . . f e 2 f f f f f f 2 e f . . 
                        . . f f f f e e e e f f f f . . 
                        . f f e f b f 4 4 f b f e f f . 
                        . f e e 4 1 f d d f 1 4 e e f . 
                        . . f e e 3 d d d d 3 e e f . . 
                        . . . f e e 4 4 4 4 e e f . . . 
                        . . e 4 f 2 2 2 2 2 2 f 4 e . . 
                        . . 4 d f 2 2 2 2 2 2 f d 4 . . 
                        . . 4 4 f 4 4 5 5 4 4 f 4 4 . . 
                        . . . . . f f f f f f . . . . . 
                        . . . . . f f . . f f . . . . .
            """),
            img("""
                . . . . . . . . . . . . . . . . 
                        . . . . . . f f f f . . . . . . 
                        . . . . f f f 2 2 f f f . . . . 
                        . . . f f f 2 2 2 2 f f f . . . 
                        . . f f f e e e e e e f f f . . 
                        . . f e e 2 2 2 2 2 2 e f f . . 
                        . f f e 2 f f f f f f 2 e f f . 
                        . f f f f f e e e e f f f f f . 
                        . . f e f b f 4 4 f b f e f . . 
                        . . f e 4 1 f d d f 1 4 e f . . 
                        . . e f e 4 d d d d 4 e f . . . 
                        . . e 4 d d e 2 2 2 2 f e f . . 
                        . . . e d d e 2 2 2 2 f 4 e . . 
                        . . . . e e f 5 5 4 4 f . . . . 
                        . . . . . f f f f f f f . . . . 
                        . . . . . . . . . f f f . . . .
            """)],
        100,
        False)
controller.down.on_event(ControllerButtonEvent.PRESSED, on_down_pressed)

projectile: Sprite = None
facingdirection = 0
myEnemy: Sprite = None
statusbar: StatusBarSprite = None
EnemyHitBoolean = 0
SwordStrength = 0
mySprite: Sprite = None
tiles.set_current_tilemap(tilemap("""
    Dungeon 1
"""))
statusbar2 = statusbars.create(20, 4, StatusBarKind.health)
mySprite = sprites.create(img("""
        . . . . . . f f f f . . . . . . 
            . . . . f f f 2 2 f f f . . . . 
            . . . f f f 2 2 2 2 f f f . . . 
            . . f f f e e e e e e f f f . . 
            . . f f e 2 2 2 2 2 2 e e f . . 
            . . f e 2 f f f f f f 2 e f . . 
            . . f f f f e e e e f f f f . . 
            . f f e f b f 4 4 f b f e f f . 
            . f e e 4 1 f d d f 1 4 e e f . 
            . . f e e 3 d d d d 3 e e f . . 
            . . . f e e 4 4 4 4 e e f . . . 
            . . e 4 f 2 2 2 2 2 2 f 4 e . . 
            . . 4 d f 2 2 2 2 2 2 f d 4 . . 
            . . 4 4 f 4 4 5 5 4 4 f 4 4 . . 
            . . . . . f f f f f f . . . . . 
            . . . . . f f . . f f . . . . .
    """),
    SpriteKind.player)
statusbar2.attach_to_sprite(mySprite)
statusbar2.set_label("HP")
statusbar2.value = 100
info.set_life(3)
SwordStrength = -20
EnemyHitBoolean = 0
statusbar = statusbars.create(20, 4, StatusBarKind.health)
myEnemy = sprites.create(img("""
        . . . . c c c c c c . . . . . . 
            . . . c 6 7 7 7 7 6 c . . . . . 
            . . c 7 7 7 7 7 7 7 7 c . . . . 
            . c 6 7 7 7 7 7 7 7 7 6 c . . . 
            . c 7 c 6 6 6 6 c 7 7 7 c . . . 
            . f 7 6 f 6 6 f 6 7 7 7 f . . . 
            . f 7 7 7 7 7 7 7 7 7 7 f . . . 
            . . f 7 7 7 7 6 c 7 7 6 f c . . 
            . . . f c c c c 7 7 6 f 7 7 c . 
            . . c 7 2 7 7 7 6 c f 7 7 7 7 c 
            . c 7 7 2 7 7 c f c 6 7 7 6 c c 
            c 1 1 1 1 7 6 f c c 6 6 6 c . . 
            f 1 1 1 1 1 6 6 c 6 6 6 6 f . . 
            f 6 1 1 1 1 1 6 6 6 6 6 c f . . 
            . f 6 1 1 1 1 1 1 6 6 6 f . . . 
            . . c c c c c c c c c f . . . .
    """),
    SpriteKind.enemy)
statusbar.attach_to_sprite(myEnemy, 0, 0)
statusbar.value = 100
statusbar.set_label("HP")
scene.camera_follow_sprite(mySprite)
controller.move_sprite(mySprite, 100, 100)
tiles.place_on_tile(mySprite, tiles.get_tile_location(15, 1))
tiles.place_on_tile(myEnemy, tiles.get_tile_location(0, 19))
myEnemy.follow(mySprite, 45)

def on_forever():
    pass
forever(on_forever)
